# Generated by Django 3.2.3 on 2021-06-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(max_length=40)),
                ('fecha', models.DateField(null=True)),
                ('imagen', models.ImageField(upload_to='atenciones')),
                ('materiales', models.TextField(max_length=40)),
                ('publicado', models.BooleanField(default=False)),
                ('comentario', models.CharField(default='N/A', max_length=40)),
                ('trabajador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('imagen_categoria', models.ImageField(upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_galeria', models.ImageField(null=True, upload_to='galeria')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.atencion')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.tipoatencion'),
        ),
    ]
