# Generated by Django 3.2.3 on 2021-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=15)),
                ('comentario', models.TextField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='diagnostico',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='materiales',
            field=models.TextField(max_length=100),
        ),
    ]
