# Generated by Django 3.2.4 on 2021-06-22 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0002_auto_20210613_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioconsulta',
            name='correo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='formularioconsulta',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='formularioconsulta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.tipoatencion'),
        ),
        migrations.AlterField(
            model_name='formularioconsulta',
            name='comentario',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
